spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rentcar
    username: postgres
    password: Bire2022
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8080



